In [1]:
# max norm
from math import inf
from numpy import array
from numpy.linalg import norm

a = array([1,2,3])
print(a)

maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0


In [2]:
a = array([1,2,3])
b = array([1,2,3])
c = a.dot(b)
print(c)

14


In [3]:
# triangular matrix
from numpy import tril
from numpy import triu

m = array([
    [1,2,3],
    [1,2,3],
    [1,2,3]]
)
print(m)
print("-"*10)
lower = tril(m)
print(lower)
print("-"*10)
upper = triu(m)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
----------
[[1 0 0]
 [1 2 0]
 [1 2 3]]
----------
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [4]:
# diagnol matrix
from numpy import diag

m = array([
    [1,2,3],
    [1,2,3],
    [1,2,3]])
d = diag(m)
print(d)
D = diag(d)
print(D)

[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [5]:
# identity matrix
from numpy import identity
i = identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# orthogonal matrix
from numpy.linalg import inv

q = array([
    [1,0],
    [0,-1]])
print(q)
print("-"*10)

v = inv(q)
print(v)
print("-"*10)
print(q.T)
print("-"*10)

I = q.dot(q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
----------
[[ 1.  0.]
 [-0. -1.]]
----------
[[ 1  0]
 [ 0 -1]]
----------
[[1 0]
 [0 1]]


In [7]:
# matrix trace
from numpy import trace

t = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
print(t)
print("-"*10)
ti = trace(t)
print(ti)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
15


In [8]:
# matrix determinant
from numpy.linalg import det

S = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
print(S)
print("-"*10)
B = det(S)
print(B)

# detrminan 0 beshe yani inverse nadaare

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
0.0


In [9]:
# vector rank
# rank: takhmini az tedad row va column haee ke mostaghel hastan
# rank 0 beshe dareh be noghteh eshareh mikone...age 1 beshe dare be khat eshareh mikone...age 2 beshe be safheh eshareh mikone
from numpy.linalg import matrix_rank 

v1= array([1,2,3])
print(v1)
print("-"*10)

vr1 = matrix_rank(v1)
print(vr1)
print("-"*10)

v2 = array([0,0,0,0,0])
print(v2)
print("-"*10)
vr2=matrix_rank(v2)
print(vr2)

[1 2 3]
----------
1
----------
[0 0 0 0 0]
----------
0


In [10]:
# sparse matrix
from scipy.sparse import csr_matrix

s = array([
    [1,0,0,1,0,0],
    [0,0,2,0,0,1],
    [0,0,0,2,0,0]])
print(s)
print("-"*10)

cs = csr_matrix(s)
print(cs)
print("-"*10)

# recostruct dense matrix
r = cs.todense()
print(r)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
----------
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (3, 6)>
  Coords	Values
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
----------
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [11]:
# sparsity calculation
from numpy import count_nonzero

c = array([
    [1,0,0,1,0,0],
    [0,0,2,0,0,1],
    [0,0,0,2,0,0]])
print(c)
print("-"*10)

sparsity = 1.0 -  count_nonzero(c) / c.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
----------
0.7222222222222222


# matrix decomposition
matrix ro be ajzaye sazandeh khodesh taghsim konim

## LU Decomposition
paeen mosalasi va bala mosalasi ro azash estekhraj mikonim

In [12]:
from numpy import array
from scipy.linalg import lu

A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

print(A, "\n")

P,L,U = lu(A)
print("P: ",P)
print("-"*50)
print("L: ",L)
print("-"*50)
print("U: ",U)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

P:  [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
--------------------------------------------------
L:  [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
--------------------------------------------------
U:  [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


## ًQR Decomposition


In [13]:
from numpy.linalg import qr

A = array([
    [1,2],
    [3,4],
    [5,6]])

Q,R = qr(A, "complete")
print(Q)
print("-"*10)
print(R)
print("-"*10)


[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
----------
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
----------


In [14]:
# Cholesky Decomposition
from numpy.linalg import cholesky

A = array([
    [2,1,1],
    [1,2,1],
    [1,1,2]])
L = cholesky(A)
print(L, "\n\n")
print (L.dot(L.T))

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]] 


[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [15]:
# Eigendecomposition
from numpy.linalg import eig

A = array([
   [1,2,3],
    [4,5,6],
    [7,8,9]])

values,vectors = eig(A)
print(values)
print("-"*10)
print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
----------
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [16]:
print(A.dot(vectors[:,0]))
print(vectors[:,0]*values[0])

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [17]:
from numpy import diag
from numpy.linalg import inv

Q = vectors
Q_inv = inv(Q)
D = diag(values)
print(Q.dot(D).dot(Q_inv))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [18]:
# Singular Value Decomposition
from numpy import array
from scipy.linalg import svd

A = array([
    [1,2],
    [3,4],
    [5,6]])

U,s,V = svd(A)
print(U)
print("-"*100)
print(s)
print("-"*100)
print(V)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
----------------------------------------------------------------------------------------------------
[9.52551809 0.51430058]
----------------------------------------------------------------------------------------------------
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [19]:
from numpy import diag, zeros

sigma = zeros((A.shape[0],A.shape[1]))
print(sigma)
sigma[:A.shape[1], :A.shape[1]] = diag(s)
print(sigma)
U.dot(sigma).dot(V)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## Expected Value and Mean

In [20]:
# vector mean
from numpy import array, mean

v = array([
    [1,2,3,4],
    [5,6,7,8]])

mean(v, axis=0)

array([3., 4., 5., 6.])

## Variance and Standard Deviation

In [21]:
from numpy import var
v= array([1,2,3,4,5,6])

var(v, ddof=1) # ddof = degree of freedom

np.float64(3.5)

In [22]:
# matrix variance



In [ ]:
# matrix standard deviation
from numpy import std


In [24]:
# vector covariance
from numpy import array
from numpy import cov

x = array([1,2,3,4,5,6,7,8])
y = array([8,7,6,5,4,3,2,1])
sigma = cov(x,y)[0,1]
print(sigma)

-6.0


In [27]:
# vector correlation
from numpy import corrcoef
x = array([1,2,3,4,5,6,7,8])
y = array([8,7,6,5,4,3,2,1])
corrcoef(x,y)[1,1]

np.float64(1.0)

In [28]:
# covariance matrix
from numpy import cov

x = array([
     #age     #loan     #score
    [10,     40,     8],
    [30,     50,     10],
    [20,     15,     7],
    [10,     10,     6],
    [5,      8,      6]])

cov(x.T)

array([[100.  , 123.75,  13.75],
       [123.75, 365.8 ,  30.7 ],
       [ 13.75,  30.7 ,   2.8 ]])